---
title: "quality_control"
format:
  html:
    theme: default
    toc: true
    number-sections: true
---

```{r}
library(dplyr)
library(ggplot2)
library(ggthemes)
library(ggforce)
```



```{r}
main_data <- read.csv("/Users/ty/Documents/Github/forest_structural_diversity/data_quality_control/forest_div_quality_control_v1.csv")
```


```{r}
n <- names(main_data)
```

```{r}
main_data |>
  ggplot() + 
  #geom_histogram() +
    geom_autodensity() +
  facet_matrix(vars(n[1:20]), layer.diag = 1) +
 theme_tufte() 
 


ggsave("qc_density_plots.pdf",
  width = 60,
  height = 60,
  units = "in",
  dpi = 600,
  limitsize = FALSE,
  bg = NULL
)
```



```{r}
main_data |>
  ggplot() + 
  #geom_histogram() +
    geom_autodensity() +
   scale_x_continuous(trans='log2') +
  facet_matrix(vars(n[1:20]), layer.diag = 1) +
 theme_tufte() 
 


ggsave("qc_LOG_X_density_plots.pdf",
  width = 60,
  height = 60,
  units = "in",
  dpi = 600,
  limitsize = FALSE,
  bg = NULL
)
```

```{r}
main_data |>
  ggplot() + 
  #geom_histogram() +
    geom_autodensity() +
   scale_y_continuous(trans='log2') +
  facet_matrix(vars(n[1:20]), layer.diag = 1) +
 theme_tufte() 
 


ggsave("qc_LOG_Y_density_plots.pdf",
  width = 60,
  height = 60,
  units = "in",
  dpi = 600,
  limitsize = FALSE,
  bg = NULL
)
```

```{r}
main_data |>
  ggplot() + 
  #geom_histogram() +
    geom_autodensity() +
   scale_x_continuous(trans='log2') +
  scale_y_continuous(trans='log2')+
  facet_matrix(vars(n[1:20]), layer.diag = 1) +
 theme_tufte() 
 


ggsave("qc_LOG_LOG_density_plots.pdf",
  width = 60,
  height = 60,
  units = "in",
  dpi = 600,
  limitsize = FALSE,
  bg = NULL
)
```

```{r}
main_data |>
  ggplot() + 
  #geom_histogram() +
    geom_autodensity() +
   scale_y_sqrt() +
  facet_matrix(vars(n[1:20]), layer.diag = 1) +
 theme_tufte() 
 


ggsave("qc_SQRT_Y_density_plots.pdf",
  width = 60,
  height = 60,
  units = "in",
  dpi = 600,
  limitsize = FALSE,
  bg = NULL
)
```



